# Generated by Django 5.0.4 on 2024-05-03 11:42

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_Ctgry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('image', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstaFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=100)),
                ('Tags', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(null=True, upload_to='media/blog')),
                ('Description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('quots', models.TextField(blank=True, max_length=500, null=True)),
                ('popular', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, default='', max_length=500, null=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog_ctgry')),
                ('instafeed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.instafeed')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blog_Post',
            },
        ),
    ]
