# Generated by Django 5.0.4 on 2024-05-03 06:32

import colorfield.fields
import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero_Featurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('icon_class', models.CharField(blank=True, max_length=100, null=True)),
                ('description', django_ckeditor_5.fields.CKEditor5Field()),
                ('link', models.CharField(blank=True, max_length=100, null=True)),
                ('color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None)),
            ],
        ),
        migrations.CreateModel(
            name='Hero_Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('short_desc', models.TextField(blank=True, max_length=250, null=True)),
                ('link', models.CharField(blank=True, max_length=100, null=True)),
                ('bg_image', models.ImageField(null=True, upload_to='media/hero_slider')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('description', django_ckeditor_5.fields.CKEditor5Field()),
                ('short_desc', models.TextField(blank=True, max_length=500, null=True)),
                ('price', models.IntegerField(default=0, null=True)),
                ('discount', models.IntegerField(default=0, null=True)),
                ('featured_video', models.CharField(max_length=100, null=True)),
                ('feature_image', models.ImageField(null=True, upload_to='media/pkg_feature')),
                ('bg_image', models.ImageField(null=True, upload_to='media/pkg_bg')),
                ('status', models.CharField(choices=[('PUBLISH', 'PUBLISH'), ('Hot deals', 'Hot deals')], max_length=50, null=True)),
                ('starting_date', models.DateField(null=True)),
                ('duration', models.CharField(max_length=50, null=True)),
                ('deadline', models.DateField(null=True)),
                ('slug', models.SlugField(blank=True, default='', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Package_Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_img', models.ImageField(null=True, upload_to='media/pkg_slider')),
                ('title', models.CharField(max_length=50, null=True)),
                ('short_desc', models.TextField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('short_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('icon_class', models.CharField(max_length=100)),
                ('icon_colour', colorfield.fields.ColorField(blank=True, default='#FF0000', image_field=None, max_length=25, null=True, samples=None)),
                ('bgPattern_colour', colorfield.fields.ColorField(blank=True, default='#FF0000', image_field=None, max_length=25, null=True, samples=None)),
                ('link', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('Description', django_ckeditor_5.fields.CKEditor5Field()),
            ],
        ),
        migrations.CreateModel(
            name='Tour_Ctgry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.package')),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.tour_ctgry'),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField(null=True)),
                ('Sub_title', models.CharField(max_length=100)),
                ('youtube_id', models.CharField(blank=True, max_length=100, null=True)),
                ('time_duration', models.CharField(blank=True, max_length=50, null=True)),
                ('preview', models.BooleanField(default=False)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.package')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.place')),
            ],
        ),
    ]
